version: "3.8"
services:
  bdd:
    image: mysql
    container_name: Abend-sql
    environment:
      - MYSQL_DATABASE=abend-core
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data-abend:/var/lib/mysql
    networks:
      - ab-net
  server:
    image: node:16
    container_name: Abend-server
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    networks:
      - ab-net
  client:
    image: node:16
    container_name: Abend-client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    networks:
      - ab-net
networks:
  ab-net:
volumes:
  db-data-abend: {}
