version: "3.8"
services:
  bdd:
    image: mysql
    container_name: Abend-sql
    environment:
      - MYSQL_DATABASE=abend-core
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data-abend:/var/lib/mysql
    networks:
      - ab-net
  server:
    image: node:18
    container_name: Abend-server
    ports:
      - "5000:5000"
    working_dir: /server
    command: "npm run dev"
    volumes:
      - ./server:/server
    networks:
      - ab-net
  client:
    build: ./client
    container_name: Abend-client
    ports:
      - "5173:5173"
    working_dir: /client
    command: "npm run dev"
    volumes:
      - ./client:/client
    networks:
      - ab-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Abend-phpmyadmin
    environment:
      - PMA_HOST=bdd
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - ab-net
networks:
  ab-net:
volumes:
  db-data-abend: {}
