services:
  bdd:
    image: mysql
    container_name: Abend-sql
    environment:
      - MYSQL_DATABASE=abend-core
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data-abend:/var/lib/mysql
    networks:
      - ab-net

  server:
    image: node:18
    container_name: Abend-server
    ports:
      - "5000:5000"
    working_dir: /server
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./server:/server
    networks:
      - ab-net
    stop_grace_period: 1s

  client:
    build: ./client
    container_name: Abend-client
    ports:
      - "5173:5173"
    working_dir: /client
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./client:/client
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - ab-net
    stop_grace_period: 1s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Abend-phpmyadmin
    environment:
      - PMA_HOST=bdd
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - ab-net
networks:
  ab-net:
volumes:
  db-data-abend: {}
