services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/letsencrypt:/letsencrypt
    environment:
      - OVH_APPLICATION_KEY=${OVH_APP_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APP_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
      - OVH_ENDPOINT=ovh-eu
    networks:
      - ab-net
    restart: unless-stopped

  bdd:
    image: mysql
    container_name: Abend-sql
    environment:
      - MYSQL_DATABASE=abend-core
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - ./db-data-abend:/var/lib/mysql
    networks:
      - ab-net

  redis:
    image: redis:7.2
    container_name: Abend-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/data
    networks:
      - ab-net
    stop_grace_period: 1s

  server:
    image: node:18
    container_name: Abend-server
    working_dir: /server
    command: sh -c "npm install && npm run prod"
    volumes:
      - ./server:/server
    environment:
      - NODE_ENV=prod
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.abnd.io`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls=true
      - traefik.http.routers.server.tls.certresolver=ovh
      - traefik.http.services.server.loadbalancer.server.port=5000
    networks:
      - ab-net
    stop_grace_period: 1s

  client:
    build: ./client
    container_name: Abend-client
    working_dir: /client
    command: sh -c "npm install && npm run prod"
    volumes:
      - ./client:/client
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`abnd.io`)
      - traefik.http.routers.client.entrypoints=websecure
      - traefik.http.routers.client.tls=true
      - traefik.http.routers.client.tls.certresolver=ovh
      - traefik.http.services.client.loadbalancer.server.port=4173
    networks:
      - ab-net
    stop_grace_period: 1s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Abend-phpmyadmin
    environment:
      - PMA_HOST=bdd
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8089:80"
    networks:
      - ab-net

networks:
  ab-net:

volumes:
  db-data-abend: {}
  redis_data: {}
