global:
  checkNewVersion: false 
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: false  # Désactive explicitement le dashboard
entryPoints:
  web:
    address: ":80"
    http:
      middlewares:
        - redirect-to-https
  websecure:
    address: ":443"
certificatesResolvers:
  ovh:
    acme:
      email: "contact@abnd.io"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: "ovh"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: "https"
        permanent: true
